Repository IloveDev-Crew/BaekJoon-Challenge, pull requests merged in 2021-08, with the labels that each got.

#2 [Test] judge Test
  test/brute_force/14500/main.java
  test/minimum_spanning_tree/4386/main.py
Labels: Simple Check Success

#3 [Test] Add 1000 java solution : judge bot test
  test/IO/1000/main.java
Labels: Simple Check Failed, Simple Check Success

#8 [Test] Add 1001 java solution : judge success test
  test/Implementation/17173/main.java
Labels: Simple Check Success

#33 [Add] 10972 : java solution
  solution/BruteForce/10972/main.java
Labels: Simple Check Success

#34 Add [10971] : java solution
  solution/DFS/10971/main.java
Labels: Simple Check Success

#35 Add [10718] : java solution(We love kriii)
  solution/IO/10718/main.java
Labels: Simple Check Success

#36 Add [2562] : java solution(최댓값)
  solution/Implementation/2562/main.java
Labels: Done

#38 [Add] 1697 : java solution(숨바꼭질) #38
  solution/BFS/13549/main.java
  solution/BFS/1697/main.java
Labels: Done

#39 Update Demo.yml
  .github/workflows/Demo.yml
  solution/BFS/13913/main.java
  solution/Math/11720/main.java
Labels: Done
